### ISSUE TITLE
Search Studies related to our argumentation plan

### ISSUE THREAD

**Issue by Super-T02** [KarylReyne/DataLiteracyWS23#31]
Please search studies which help us to make strong arguments in our context. For this please refer to ![Datasets.pdf](https://github.com/KarylReyne/DataLiteracyWS23/files/13863791/Datasets.pdf) where our main argumentation goal is documented. 

Examples may be: [Schulleiter zu Risiken an Schulen](https://www.vbe.de/fileadmin/user_upload/VBE/Service/Meinungsumfragen/2021-11-26_forsa-Befragung_Schulleitungen_Bericht.pdf)

Document all sources and make a short summary of what they are argueing, s.t. we can later refer to them.

**Comment by L-Kasu** [comment]
https://www.tandfonline.com/doi/epdf/10.1080/21568235.2020.1718516?needAccess=true
Arguing that grade deflation in german universities is a result of cyclic dynamics int the time series. In the period of grade increase the grades increse more than they decrease.

**Comment by L-Kasu** [comment]
https://www.vr-elibrary.de/doi/epdf/10.7788/bue-2015-0407
Investigating the grade deflation of Abitur grades and compare it to unversity applications. No explanation for better grades is found and asking for future work.

**Comment by L-Kasu** [comment]
https://www.econstor.eu/bitstream/10419/61676/1/722307225.pdf
Increased competition between universities does not cause grade inflation.

**Comment by L-Kasu** [comment]
https://www.degruyter.com/document/doi/10.1515/ordo-2015-0103/html
arguing that grade inflation can not be proven. Competence of students has also increased

**Comment by L-Kasu** [comment]
https://poorvucenter.yale.edu/sites/default/files/basic-page-supplementary-materials-files/2002-kohn-dangerous_myth_of_grade_inflation.pdf
an essay, but making a good argument. It argues that grad inflation is a myth and grad don't actually predict career success or competence reliably.

**Comment by L-Kasu** [comment]
https://www.sciencedirect.com/science/article/pii/S0272775712000301
University grades can be predicted by using high school grades.

**Comment by L-Kasu** [comment]
https://journals.sagepub.com/doi/full/10.1177/1469787418819728
grading does not improve motivation of students. The contrary is the case. Pass/fail is better.

**Comment by L-Kasu** [comment]
https://iaap-journals.onlinelibrary.wiley.com/doi/abs/10.1111/j.1464-0597.1990.tb01039.x
predictive value of school grade. A meta analysis.

**Comment by L-Kasu** [comment]
https://journals.sagepub.com/doi/full/10.1177/1474904116630754
analyses the effects of the pisa study on germany. Their views of how to solve the problem (i.e., the drop in results) were also similar: increased management and control of parts of the education system, albeit by different means.

**Comment by L-Kasu** [comment]
https://www.econstor.eu/handle/10419/206955
This paper, first, informs about important policy reforms following the PISA shock in 2000. It further gives a description of the current situation and persisting inequalities at secondary schools, with particular attention paid to students with migratory backgrounds.

**Comment by L-Kasu** [comment]
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=555954
The analysis shows that German students have on average a more favorable background except for the lowest deciles, but experience much lower returns to these background characteristics in terms of test scores than Finnish students. The results imply that early streaming in Germany penalizes students in lower school types and leads to a greater inequality of educational achievement. It remains unclear, however, if this can be attributed to the effect of school types per se or student background and innate ability that determine the allocation process of students into school types. Overall, the variation in test scores can be explained much better by the observable characteristics in Germany than in Finland.

**Comment by L-Kasu** [comment]
https://www.beltz.de/fachmedien/paedagogik/zeitschriften/paedagogik.html?tx_beltz_journal%5Bcontroller%5D=Journal&tx_beltz_journal%5Baction%5D=article&tx_beltz_journal%5Barticle%5D=42286&cHash=9624ec2f40a50cceb08860ca5cf49bc6
Dass in den letzten Jahren wieder viele Lehrerstellen unbesetzt blieben und vielerorts durch Seiten-/Quereinsteiger oder durch befristete Vertretungen notdürftig Abhilfe geschaffen wird, ist bekannt. Welche Auswirkungen wird diese noch einige Zeit anhaltende Mangelsituation auf die Belastung der Lehrerinnen und Lehrer im Dienst haben? Muss man davon ausgehen, dass sich die Situation verschlechtert?

**Comment by L-Kasu** [comment]
https://www.svz.de/deutschland-welt/meinung/artikel/ist-der-lehrermangel-ein-deckmantel-44606607
Lehrerverbände und Gewerkschaften beklagen einen Personalmangel an Schulen. Statistiken zeigen jedoch: Niemals zuvor gab es mehr Lehrkräfte. Unser Autor fragt, ob die Probleme nicht eher bei Organisation, Struktur und „Mindset“ zu suchen sind.

**Comment by L-Kasu** [comment]
https://www.oecd-ilibrary.org/content/paper/246402531617
the report indicates that in countries where there are measures to hold students, teachers, and schools accountable, and where schools have a certain level of autonomy, students tend to perform better academically. The specific types of accountability and autonomy policies matter, and the report provides insights into which ones are associated with improved student achievement.

**Comment by L-Kasu** [comment]
Relation between school budgeting and performance is hard to find anything for germany. For other countries it's not really relevant imo, since they have other ways of financing schools and other school systems.

**Comment by L-Kasu** [comment]
https://connect.springerpub.com/content/sgrjcep/14/3/343.abstract
Performance of Students With Special Educational Needs in Germany: Findings From Programme for International Student Assessment 2012 (PISA). Support the claim that children with special needs perform better

**Comment by L-Kasu** [comment]
https://www.pedocs.de/volltexte/2022/25616/pdf/DDS_2010_1_Klemm_Zur_Entwicklung_des_Lehrerinnen_und_Lehrerbedarfs.pdf
Zur Entwicklung des Lehrerbedarfs. Ist halt von 2010 also vielleicht useless
.

**Comment by L-Kasu** [comment]
https://www.bildungsserver.de/Lehrerbedarf-und-Lehrerbedarfsprognosen-in-den-Bundeslaendern-5530-de.html#Modellrechnung_und_Beschluesse_der_Kultusministerkonferenz_KMK_
Lehrerbedarfsprognose der Kultusministerkonferenz.
